apiVersion: apps/v1
kind: Deployment
metadata:
  name: skill-pod-final
spec:
  replicas: 3
  selector:
    matchLabels:
      app: skill-pod-final
  template:
    metadata:
      labels:
        app: skill-pod-final
    spec:
      containers:
        - name: skillsync-container
          image: kumarreddy1902/skill-sync-image:latest
          ports:
            - containerPort: 5000

