apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: skillsync-ingress
spec:
  rules:
    - host: skillsync.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: skillsync-service
                port:
                  number: 80

