apiVersion: v1
kind: Service
metadata:
  name: skillsync-service
  labels:
    app: skillsync
spec:
  type: NodePort 
  selector:
    app: skill-app
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  
