apiVersion: v1
kind: Service
metadata:
  name: skillsync-service
  labels:
    app: skill-pod-final 
spec:
  type: ClusterIP 
  selector:
    app: skill-pod-final
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP 
